# Generated by Django 4.2.15 on 2024-09-03 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gid',
            new_name='id',
        ),
    ]
