# Generated by Django 4.2.17 on 2025-01-25 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0002_rename_gid_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('picture', models.ImageField(blank=True, default='media/defaults/logo.png', null=True, upload_to='profiles/<django.db.models.fields.related.OneToOneField>/')),
                ('isPictureUpdated', models.BooleanField(default=False)),
                ('isPictureApproved', models.BooleanField(default=True)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
