# Generated by Django 4.2.17 on 2025-01-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='defaults/logo.png', null=True, upload_to='profiles/<django.db.models.fields.related.OneToOneField>/'),
        ),
    ]
