# Generated by Django 4.2.17 on 2025-01-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_picture',
            field=models.ImageField(blank=True, default='defaults/logo.png', null=True, upload_to='profiles/<django.db.models.fields.related.OneToOneField>/'),
        ),
    ]
