# Generated by Django 4.2.17 on 2025-01-25 23:57

from django.db import migrations, models
import usermodel.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0005_profile_default_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_picture',
            field=models.ImageField(blank=True, default='defaults/logo.png', null=True, upload_to=usermodel.models.Profile.profile_picture_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='defaults/logo.png', null=True, upload_to=usermodel.models.Profile.profile_picture_path),
        ),
    ]
