# Generated by Django 4.2.13 on 2024-06-26 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('isImageAdminApproved', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Candles',
                'ordering': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this maker')),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Makers',
                'ordering': ['name', '-date_added'],
            },
        ),
        migrations.CreateModel(
            name='ScentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the scent (use underscores instead of spaces', max_length=255, unique=True)),
                ('note_type', models.CharField(blank=True, choices=[('d', 'Default'), ('t', 'Top Note'), ('m', 'Middle Note'), ('b', 'Base Note')], default='d', help_text='Type of Note', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Scent Notes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, 'no rate'), (1, 'one star'), (2, 'two stars'), (3, 'three stars'), (4, 'four stars'), (5, 'five stars')], default=0, help_text='With 5 being the best, what do you rate this candle?')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('isVisible', models.BooleanField(blank=True, default=True)),
                ('candle_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mymainapp.candle')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('gid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='The title of the list', max_length=255)),
                ('list_type', models.IntegerField(choices=[(0, 'custom'), (1, 'have'), (2, 'had'), (3, 'want')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('candles_of_list', models.ManyToManyField(blank=True, to='mymainapp.candle')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_modified'],
            },
        ),
        migrations.AddField(
            model_name='candle',
            name='maker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='mymainapp.maker'),
        ),
        migrations.AddField(
            model_name='candle',
            name='notes',
            field=models.ManyToManyField(blank=True, help_text='Enter in the fragrance notes listed on the label of the candle', to='mymainapp.scentnote'),
        ),
    ]
