# Generated by Django 4.2.13 on 2024-06-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymainapp', '0003_candle_candle_image_scentnote_scentnote_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='candles_of_list',
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('candle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymainapp.candle')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymainapp.list')),
            ],
            options={
                'ordering': ['-date_added'],
                'unique_together': {('list_id', 'candle_id')},
            },
        ),
    ]
