# Generated by Django 4.2.13 on 2024-07-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymainapp', '0005_review_report_points_alter_list_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maker',
            new_name='Brand',
        ),
    ]
