# Generated by Django 4.2.13 on 2024-07-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymainapp', '0007_rename_maker_id_candle_brand_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user_id',
            new_name='Reporter',
        ),
        migrations.AddField(
            model_name='report',
            name='isReviewed',
            field=models.BooleanField(default=False),
        ),
    ]
