# Generated by Django 4.2.13 on 2024-07-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymainapp', '0008_rename_user_id_report_reporter_report_isreviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Reporter',
            new_name='reporter',
        ),
    ]
