# Generated by Django 4.2.14 on 2024-08-28 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymainapp', '0010_scentnotefamily_scentnotegenre'),
    ]

    operations = [
        migrations.AddField(
            model_name='scentnote',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genres', to='mymainapp.scentnotegenre'),
        ),
        migrations.AddField(
            model_name='scentnotegenre',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='families', to='mymainapp.scentnotefamily'),
        ),
    ]
