# Generated by Django 4.2.14 on 2024-08-29 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymainapp', '0011_scentnote_genre_scentnotegenre_family'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScentNoteFamily',
            new_name='ScentFamily',
        ),
        migrations.RenameModel(
            old_name='ScentNoteGenre',
            new_name='ScentGenre',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name', '-date_added'], 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterField(
            model_name='list',
            name='list_type',
            field=models.IntegerField(choices=[(0, 'custom'), (1, 'have'), (2, 'had'), (3, 'want'), (4, 'favorites')], default=0),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mymainapp.list'),
        ),
    ]
