# Generated by Django 4.2.14 on 2024-08-30 04:05

from django.db import migrations, models
import django.db.models.deletion
import mymainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mymainapp', '0012_rename_scentnotefamily_scentfamily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mymainapp.list', validators=[mymainapp.models.limit_favorites_listitems]),
        ),
    ]
