# Generated by Django 4.2.15 on 2024-10-16 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mymainapp.models.brands


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymainapp', '0013_alter_listitem_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'review_id')},
        ),
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('year_founded', models.CharField(blank=True, max_length=4, null=True)),
                ('brand_logo', models.ImageField(blank=True, upload_to=mymainapp.models.brands.BrandProfile.folder_path_brand_profile)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='mymainapp.brand')),
            ],
            options={
                'verbose_name_plural': 'Brand Profiles',
            },
        ),
    ]
