# Generated by Django 4.2.17 on 2025-01-22 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymainapp', '0016_review_love_count_reviewlove'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewLove',
            new_name='ReviewLike',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='love_count',
            new_name='like_count',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
