# Generated by Django 4.2.17 on 2025-01-22 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymainapp', '0017_rename_reviewlove_reviewlike_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
        migrations.CreateModel(
            name='CandleExperienceVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold_throw_rating', models.IntegerField(choices=[(0, 'no rate'), (1, 'low'), (2, 'medium'), (3, 'high')], default=0, help_text='Vote on how strong candle scent is while not burning')),
                ('warm_throw_rating', models.IntegerField(choices=[(0, 'no rate'), (1, 'low'), (2, 'medium'), (3, 'high')], default=0, help_text='Vote on how strong candle scent is while burning')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('candle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymainapp.candle')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-modified_at'],
                'unique_together': {('user_id', 'candle_id')},
            },
        ),
    ]
