# Generated by Django 4.2.17 on 2025-01-26 05:24

from django.db import migrations, models
import mymainapp.models.profanity_validator


class Migration(migrations.Migration):

    dependencies = [
        ('mymainapp', '0018_alter_notification_options_candleexperiencevote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(validators=[mymainapp.models.profanity_validator.validate_profanity]),
        ),
    ]
